name: Daily Bonus

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 23 * * *'

jobs:
  checkin:
    strategy:
      matrix:
        # os: [ubuntu-latest]
        # os: [ubuntu-latest, self-hosted]
        os: [self-hosted]

    runs-on: ${{ matrix.os }}

    env:
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
      YURIFANS_EMAIL: ${{ secrets.YURIFANS_EMAIL }}
      YURIFANS_PASSWORD: ${{ secrets.YURIFANS_PASSWORD }}
      PICA_EMAIL: ${{ secrets.PICA_EMAIL }}
      PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TZ: "Asia/Shanghai"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Echo current time
        run: |
          echo "当前时区时间:"
          date
          echo "时区信息:"
          ls -l /etc/localtime
      
      # 配置 pip 全局镜像（可选）
      - name: Configure pip mirror
        run: |
          python3.8 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          python3.8 -m pip config set global.extra-index-url https://mirrors.aliyun.com/pypi/simple
          python3.8 -m pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn
          python3.8 -m pip config set global.trusted-host mirrors.aliyun.com

      - name: Use preinstalled Python
        run: |
          python3.8 --version
          python3.8 -m pip install -r requirements.txt


      - name: Check-in
        run: python3.8 ./message.py
